### ISSUE TITLE
Is this in use?

### ISSUE THREAD

**Issue by jamiejackson** [markussackmann/extension-redis-single#1]
@markussackmann are you using this? (Anybody else?)

I'm looking for options. I see that Ortus came out with a commercial solution in January, so maybe the Lucee community didn't come up with a user-friendly FOSS solution.

**Comment by markussackmann** [comment]
We are using it in production for session storage and query cache. There is another extension for redis sentinel: https://github.com/lucee/extension-redis

**Comment by jamiejackson** [comment]
That's good to know, thanks. Sometimes, it's hard to tell if a GitHub project is abandoned or if it works solidly and hasn't needed updates in a while.

Are there any caveats that you know of, since you've been using it?

Also, have you happened to use this in Dockerized Lucee? I'm working on it, and am having a bit of trouble figuring out (via automation during the docker build) when the extension installation is complete. (This is always a problem with Lucee extensions, as the installation process is opaque.) I can throw a long "sleep" in there, but I'm trying to find a better way. If you haven't, I'll post back if/when I find a solution.

Update: Work in progress, but it works: https://github.com/jamiejackson/lucee5-install-extensions
