### ISSUE TITLE
Custom Settings

### ISSUE THREAD

**Issue by jamiejackson** [markussackmann/extension-redis-single#2]
Hi @markussackmann ,

We'll probably use your extension for our session persistence, but I wonder about some of the custom options.

Would you be able to provide a quick description of the important ones? I also wonder if there is interplay between the settings within the extension and between Lucee and the extension. (E.g., your Lucee configuration `foo` must be set smaller than the extension's `foo` setting, etc.)

I figure if you can provide a few sentences of explanation, it could easily give me (and other users) at least a half-day of jumpstart on the research.

```js
this.cache.connections["session"] = {
	  class: 'lucee.extension.io.cache.redis.RedisCache'
	, storage: true
	, custom: {
		"setMinIdle":"16",
		"setTestOnReturn":"true",
		"setMinEvictableIdleTimeMillis":"60000",
		"setNumTestsPerEvictionRun":"3",
		"setTestWhileIdle":"true",
		"setTimeBetweenEvictionRunsMillis":"30000",
		"setMaxTotal":"128",
		"setBlockWhenExhausted":"true",
		"hosts":"redis:6379",
		"setTestOnBorrow":"true",
		"namespace":"lucee:session",
		"setMaxIdle":"128"
	}
	, default: 'object'
};
```

**Comment by markussackmann** [comment]
Hi @jamiejackson,

custom options are for the ObjectPool this extension uses and do not affect the configuration of redis:
http://commons.apache.org/proper/commons-pool/api-2.6.0/org/apache/commons/pool2/impl/BaseGenericObjectPool.html

Options set in Lucee Server Admin can be overwritten in Application.cfc.
